using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
using TimelessEchoes.Upgrades;
namespace Vasteria.StyleLab {
 internal sealed class Study : IDisposable {
  readonly VisualElement root; readonly StudyModel m; readonly Texture2D backdrop; readonly bool large; readonly string locale; bool mode,dark,narrow; string phoneTab="mix"; readonly Dictionary<string,Vector2> collectionOffsets=new(); string renderedTab; VisualElement dialogInvoker; public string CollectionTab="resources"; VisualElement ingredients,collection,brew,modal; ScrollView foodScroll; Label selection,stewGain; Button mix; readonly Dictionary<string,string> copy;
  [Serializable] class Catalog { public Entry[] entries; } [Serializable] class Entry {public string key,value;}
  public Study(VisualElement parent,StudyModel model,bool cauldron,bool dark,float textScale,string locale){m=model;mode=cauldron;this.dark=dark;large=textScale>1;this.locale=locale;copy=JsonUtility.FromJson<Catalog>(File.ReadAllText(VasteriaStyleLab.Folder+"Copy."+locale+".json")).entries.ToDictionary(x=>x.key,x=>x.value);root=new VisualElement{name="style-study"};root.AddToClassList("study");root.styleSheets.Add(AssetDatabase.LoadAssetAtPath<StyleSheet>(VasteriaStyleLab.Folder+"StyleStudy.uss"));root.style.unityFontDefinition=FontDefinition.FromFont(AssetDatabase.LoadAssetAtPath<Font>("Assets/TextMesh Pro/Fonts/LiberationSans.ttf"));parent.Add(root);root.RegisterCallback<PointerDownEvent>(_=>root.RemoveFromClassList("keyboard"),TrickleDown.TrickleDown);root.RegisterCallback<KeyDownEvent>(_=>root.AddToClassList("keyboard"),TrickleDown.TrickleDown);narrow=parent.style.width.value.value<=600&&parent.style.width.value.value>0;root.RegisterCallback<GeometryChangedEvent>(e=>{bool n=e.newRect.width<700;if(n!=narrow){narrow=n;Rebuild();}});var path=VasteriaStyleLab.Folder+"ReferenceViewport.png";if(File.Exists(path)){backdrop=new Texture2D(2,2);backdrop.LoadImage(File.ReadAllBytes(path));backdrop.filterMode=FilterMode.Point;}Rebuild();}
  string T(string key)=>copy.TryGetValue(key,out var s)?s:key;
  string N(double value)=>value.ToString("N0",System.Globalization.CultureInfo.GetCultureInfo(locale));
  string Short(double value)=>value>=1000000?(value/1000000).ToString("0.##")+"m":value>=1000?(value/1000).ToString("0.#")+"k":N(value);
  VisualElement E(VisualElement p,string classes,string name=null){var e=new VisualElement{name=name};foreach(var c in classes.Split(' '))if(c!="")e.AddToClassList(c);p.Add(e);return e;}
  Label L(VisualElement p,string text,string classes="body"){var e=new Label(text);foreach(var c in classes.Split(' '))if(c!="")e.AddToClassList(c);p.Add(e);return e;}
  Button B(VisualElement p,string text,Action action,string classes=""){var b=new Button(action){text=text};b.AddToClassList("button");foreach(var c in classes.Split(' '))if(c!="")b.AddToClassList(c);p.Add(b);return b;}
  Image Icon(VisualElement p,Sprite sprite,int size=40){var i=new Image{sprite=sprite,scaleMode=ScaleMode.ScaleToFit,pickingMode=PickingMode.Ignore};i.AddToClassList("icon");i.style.width=size;i.style.height=size;p.Add(i);return i;}
  ScrollView Scroll(VisualElement p,string name){var s=new ScrollView(ScrollViewMode.Vertical){name=name,verticalScrollerVisibility=ScrollerVisibility.Hidden,horizontalScrollerVisibility=ScrollerVisibility.Hidden};s.AddToClassList("scroll");s.focusable=true;s.RegisterCallback<KeyDownEvent>(e=>{float y=s.scrollOffset.y;switch(e.keyCode){case KeyCode.End:y=s.verticalScroller.highValue;break;case KeyCode.Home:y=0;break;case KeyCode.PageDown:y+=s.contentViewport.layout.height*.85f;break;case KeyCode.PageUp:y-=s.contentViewport.layout.height*.85f;break;default:return;}s.scrollOffset=new Vector2(0,y);e.StopPropagation();});p.Add(s);return s;}
  void Bar(VisualElement p,float value,string cls=""){var t=E(p,"track "+cls);var f=E(t,"fill");f.style.width=Length.Percent(value);}
  public void SetTheme(bool value){dark=value;root.EnableInClassList("dark",dark);root.EnableInClassList("light",!dark);}
  public void Dispose(){root.RemoveFromHierarchy();if(backdrop)UnityEngine.Object.DestroyImmediate(backdrop);}
  public void Rebuild(){root.Clear();root.EnableInClassList("narrow",narrow);root.EnableInClassList("large",large);SetTheme(dark);var bg=E(root,"landscape");if(backdrop){var i=new Image{image=backdrop,scaleMode=ScaleMode.ScaleAndCrop};i.AddToClassList("landscape-image");bg.Add(i);}if(mode)E(root,"shade");Navigation();if(mode)Cauldron();else Run();}
  void Navigation(){var nav=E(root,"navigation row between");nav.RegisterCallback<GeometryChangedEvent>(e=>{var hud=root.Q(className:"run-screen");if(hud!=null)hud.style.top=e.newRect.yMax+8;});var links=E(nav,"row nav-links");B(links,T("adventure"),()=>{mode=false;Rebuild();},!mode?"active":"");B(links,T("cauldron"),()=>{mode=true;Rebuild();},mode?"active":"");if(!narrow){foreach(var key in new[]{"hub","quests","library"}){var b=B(links,T(key),()=>{},"quiet");b.SetEnabled(false);b.tooltip=T("outside");}if(!mode)RunProgress(links);}if(mode)B(nav,T("back"),()=>{mode=false;Rebuild();},"nav-return");else{var returns=E(nav,"return-actions");B(returns,T("returnTown"),()=>{mode=true;Rebuild();},"retreat-action");B(returns,T("returnDeath"),()=>{var d=Dialog(T("returnDeath"));L(d,T("previewOnly"),"muted");B(d,T("close"),CloseDialog).Focus();},"death-return-action");}}
  void Cauldron(){var page=E(root,"cauldron surface","cauldron-page");if(narrow)Tabs(page,new[]{"mix","taste","collection"},phoneTab,k=>{phoneTab=k;Rebuild();});var work=E(page,"workspace row","workspace");ingredients=E(work,"column ingredients");brew=E(work,"column brewing");collection=E(work,"column collection");if(narrow){ingredients.style.display=phoneTab=="mix"?DisplayStyle.Flex:DisplayStyle.None;brew.style.display=phoneTab=="taste"?DisplayStyle.Flex:DisplayStyle.None;collection.style.display=phoneTab=="collection"?DisplayStyle.Flex:DisplayStyle.None;}Ingredients();Brewing();Collection();}
  void Tabs(VisualElement p,string[] keys,string selected,Action<string> select){var row=E(p,"row tabs");var buttons=new List<Button>();foreach(var key in keys){string k=key;var b=B(row,T(k),()=>select(k),k==selected?"tab active":"tab");buttons.Add(b);}buttons[buttons.Count-1].AddToClassList("last-tab");for(int i=0;i<buttons.Count;i++){int index=i;buttons[i].RegisterCallback<KeyDownEvent>(e=>{if(e.keyCode!=KeyCode.LeftArrow&&e.keyCode!=KeyCode.RightArrow)return;int next=(index+(e.keyCode==KeyCode.RightArrow?1:keys.Length-1))%keys.Length;select(keys[next]);root.schedule.Execute(()=>root.Query<Button>(className:"tab").ToList().FirstOrDefault(b=>b.text==T(keys[next]))?.Focus());e.StopPropagation();});}}
  void Ingredients(){ingredients.Clear();L(ingredients,T("ingredients"),"heading");foodScroll=Scroll(ingredients,"ingredients-scroll");RefreshFoods();var footer=E(ingredients,"mix-footer");var summary=E(footer,"row mix-summary");selection=L(summary,"","selection");stewGain=L(summary,"","stew-gain");RefreshSelection();mix=B(footer,T("mix"),()=>ConfirmMix(false),"primary");mix.name="mix-selected";mix.SetEnabled(m.CanMix);var all=B(footer,T("mixAll"),()=>ConfirmMix(true),"quiet");all.name="mix-all";all.SetEnabled(m.MixTargets(true).Length>0);}
  void RefreshSelection(){selection.text=(m.First?m.First.name:T("chooseFirst"))+" + "+(m.Second?m.Second.name:T("chooseSecond"));stewGain.text=m.CanMix?"+"+N(m.Value(m.First)+m.Value(m.Second))+" "+T("stew"):"";selection.tooltip=m.CanMix?selection.text:T("twoFoods");mix?.SetEnabled(m.CanMix);}
  void RefreshFoods(){foodScroll.Clear();var grid=E(foodScroll,"food-grid");var foods=m.Foods;foreach(var r in foods){var item=B(grid,"",()=>{m.Select(r);RefreshFoods();RefreshSelection();},"food "+(r==m.First||r==m.Second?"selected":""));item.name="food-"+r.name;Icon(item,r.icon,40);L(item,r.name,"small strong");L(item,Short(m.Amounts[r]),"small muted");item.tooltip=r.name+" · "+N(m.Amounts[r]);item.SetEnabled(m.Amounts[r]>0);}}
  void ConfirmMix(bool all)
  {
   var targets=m.MixTargets(all);if(targets.Length==0)return;
   string action=all?string.Format(T("mixPairs"),targets.Length/2):T("confirm");
   var box=Dialog(all?string.Format(T("mixPairs"),targets.Length/2):T("mix"));box.AddToClassList("mix-dialog");
   L(box,string.Format(T("consumeStacks"),targets.Length),"muted confirmation-copy");
   var list=Scroll(box,"confirmation-items");list.style.height=Mathf.Min(narrow?216:288,targets.Length*40);list.style.maxHeight=narrow?216:288;list.style.minHeight=72;
   foreach(var r in targets){var row=E(list,"row confirmation-item");Icon(row,r.icon,24);L(row,r.name,"small confirmation-name");L(row,N(m.Amounts[r]),"small confirmation-count");}
   var total=E(box,"row between confirmation-total");L(total,T("stew"),"muted");L(total,"+"+N(targets.Sum(m.Value)),"heading");
   var actions=E(box,"row actions");var cancel=B(actions,T("cancel"),CloseDialog,"quiet");cancel.name="cancel-mix";cancel.AddToClassList("cancel-action");
   B(actions,action,()=>{m.Mix(targets);CloseDialog();Ingredients();Brewing();},"primary").name="confirm-mix";cancel.Focus();
  }
  VisualElement Dialog(string title){CloseDialog();dialogInvoker=root.panel?.focusController.focusedElement as VisualElement;root.Q(className:"navigation")?.SetEnabled(false);root.Q(className:mode?"cauldron":"run-screen")?.SetEnabled(false);modal=E(root,"modal");var box=E(modal,"surface dialog");L(box,title,"heading");modal.RegisterCallback<KeyDownEvent>(e=>{if(e.keyCode==KeyCode.Escape){CloseDialog();e.StopPropagation();}});return box;}
  void CloseDialog(){if(modal==null)return;modal.RemoveFromHierarchy();modal=null;root.Q(className:"navigation")?.SetEnabled(true);root.Q(className:mode?"cauldron":"run-screen")?.SetEnabled(true);dialogInvoker?.Focus();}
  void Brewing(){brew.Clear();L(brew,T("taste"),"heading");var eva=E(brew,"row eva tasting-eva");Icon(eva,m.Definition.portrait.At(0),40);var evaInfo=E(eva,"eva-info");L(evaInfo,T("level")+" 733","strong");Bar(evaInfo,14.2f);L(evaInfo,"1,045 / 7,370 XP","small muted");var scroll=Scroll(brew,"tasting-scroll");var hero=E(scroll,"brew-summary");Icon(hero,m.Definition.pot.At(0),92);L(hero,Short(m.Stew),"amount");L(hero,T("stew"),"muted");L(scroll,T(m.Tasting?"tasting":"paused"),"status");var rate=E(scroll,"row between readout");L(rate,T("rate"),"muted");L(rate,N(m.Config.rollsPerSecond)+" / s","strong");var cost=E(scroll,"row between readout");L(cost,T("cost"),"muted");L(cost,N(m.Config.stewPerRoll)+" "+T("stew")+" / "+T("tasteOne"),"strong");var toggle=B(scroll,T(m.Tasting?"pause":"start"),()=>{m.Tasting=!m.Tasting;Brewing();},"primary");toggle.name="toggle-tasting";toggle.SetEnabled(m.Stew>=m.Config.stewPerRoll);if(m.Stew==0)L(scroll,T("needStew"),"muted");var odds=E(scroll,"odds");var oddsHeading=E(odds,"row between odds-heading");L(oddsHeading,T("odds"),"strong");var info=B(oddsHeading,"i",()=>{var d=Dialog(T("details"));L(d,T("tasteDetail"),"muted");B(d,T("close"),CloseDialog).Focus();},"quiet details-button");info.tooltip=T("details");var entries=m.Odds();float total=entries.Sum(x=>x.weight);foreach(var o in entries){var row=E(odds,"row between odds-row");L(row,T(o.key));L(row,(100*o.weight/total).ToString("0.0")+"%","strong");}}
  void Collection(){var previous=collection.Q<ScrollView>("collection-scroll");if(previous!=null&&renderedTab!=null)collectionOffsets[renderedTab]=previous.scrollOffset;collection.Clear();renderedTab=CollectionTab;L(collection,T("collection"),"heading");Tabs(collection,new[]{"resources","buffs","eternal"},CollectionTab,k=>{CollectionTab=k;Collection();});{var legend=E(collection,"row legend");if(CollectionTab=="eternal")legend.style.visibility=Visibility.Hidden;for(int i=1;i<=8;i++){var swatch=L(legend,"T"+i,"tier-swatch rarity-badge tier-"+i);swatch.tooltip=T("tier")+" "+i;}}var scroll=Scroll(collection,"collection-scroll");if(collectionOffsets.TryGetValue(CollectionTab,out var offset))scroll.schedule.Execute(()=>scroll.scrollOffset=offset).StartingIn(30);if(CollectionTab=="resources"){foreach(var group in m.Resources.Where(r=>!r.DisableAlterEcho).GroupBy(r=>m.Groups[r])){int min=m.GroupTier(group.Select(r=>"RES:"+r.name));var head=E(scroll,"row between group-heading");L(head,T(group.Key),"strong");var bonus=E(head,"row section-bonus tier-"+min);bonus.tooltip=T("tier")+" "+min;bonus.Add(new RarityStar());L(bonus,"+"+(min*.1f).ToString("0.0")+"%","small muted");var grid=E(scroll,"card-grid");foreach(var r in group)Card(grid,r.name,r.icon,"RES:"+r.name);}}else if(CollectionTab=="buffs"){int min=m.GroupTier(m.Buffs.Select(b=>"BUFF:"+b.name));var head=E(scroll,"row between group-heading");L(head,T("buffs"),"strong");var bonus=E(head,"row section-bonus tier-"+min);bonus.tooltip=T("tier")+" "+min+" · "+T("buffPower");bonus.Add(new RarityStar());L(bonus,"+"+(min*2.5f).ToString("0.0")+"%","small muted");var grid=E(scroll,"card-grid");foreach(var b in m.Buffs)Card(grid,b.title,b.buffIcon,"BUFF:"+b.name);}else{L(scroll,T(m.InfinityActive?"eternalActive":"eternalLocked"),"strong group-heading");if(!m.InfinityActive)L(scroll,T("eternalRequirement"),"muted");foreach(var b in m.Boons){var row=E(scroll,"row boon");Icon(row,b.Icon,40);var text=E(row,"grow");L(text,b.DisplayName,"strong");int count=m.Count("INF:"+b.Stat);L(text,N(count)+" "+T("cards"),"small muted");L(row,"+"+Math.Pow(count,b.Exponent).ToString("F"+b.DecimalPlaces)+(b.IsPercent?"%":""),"strong");}}}
  void Card(VisualElement grid,string title,Sprite icon,string id){int tier=m.Tier(id);var card=B(grid,"",()=>{var d=Dialog(title+" · T"+tier);Icon(d,icon,64);L(d,N(m.Count(id))+" / "+N(m.Next(id))+" "+T("cards"));int index=Mathf.Clamp(tier-1,0,7);if(tier>0){if(id.StartsWith("RES:"))L(d,"+"+m.Config.resourceYieldBonusPerTier[index]+"% "+T("echoPower"));else{L(d,"−"+m.Config.buffCooldownReductionPerTier[index]+"% "+T("cooldown"));L(d,"+"+m.Config.buffPowerBonusPerTier[index]+"% "+T("buffPower"));}}B(d,T("close"),CloseDialog).Focus();},"card tier-"+tier);var identity=E(card,"card-identity");identity.tooltip=T("tier")+" "+tier;Icon(identity,icon,36);L(card,title,"small strong card-name");L(card,m.Tiers.IsMaxed(id)?T("max"):Short(m.Count(id))+" / "+Short(m.Next(id)),"small muted");var progress=E(card,"row card-progress-row");progress.Add(new RarityStar());Bar(progress,100*m.Tiers.GetTierProgress(id),"collection-progress");card.tooltip=title+" · "+T("tier")+" "+tier+" · "+(m.Tiers.IsMaxed(id)?T("max"):N(m.Count(id))+" / "+N(m.Next(id)));}
  void Metric(VisualElement p,string value,string key){var e=E(p,"metric");L(e,value,"strong");L(e,T(key),"small muted");}
  void RunProgress(VisualElement parent){var location=E(parent,"location");location.tooltip=T("farmlands");var navigation=AssetDatabase.LoadAssetAtPath<TimelessEchoes.UI.Toolkit.ToolkitNavigationDefinition>("Assets/UI/Toolkit/Navigation.asset");var route=E(location,"route-progress");Bar(route,50f);var runner=Icon(route,navigation.progressHero,64);runner.AddToClassList("route-hero");runner.style.left=Length.Percent(50);runner.style.marginLeft=-40;var reaper=Icon(route,navigation.progressReaper,80);reaper.AddToClassList("route-reaper");reaper.style.scale=new Scale(new Vector3(-1,1,1));L(location,"2,323 / 4,645","small strong");}
  void Run(){var screen=E(root,"run-screen");if(narrow)RunProgress(screen);var lower=E(screen,"hero-corner");var skills=E(lower,"row abilities");string[] names={"Echo Tasks","Task Speed","Movement Speed","Prospector","Echo Resonance"};string[] times={"51s","10s","9s","1:21","2:06"};for(int i=0;i<5;i++){int index=i;var recipe=m.Buffs.FirstOrDefault(b=>b.name.Replace("|","").Replace(" ","").Equals(names[i].Replace(" ",""),StringComparison.OrdinalIgnoreCase)||b.title==names[i]);var b=B(skills,"",()=>{m.AutoCast[index]=!m.AutoCast[index];Rebuild();},"ability"+(i==4?" last-ability":""));b.tooltip=names[i]+" · "+T(m.AutoCast[i]?"auto":"manual");Icon(b,recipe?recipe.buffIcon:m.Run.portrait,30);L(b,times[i],"small strong");b.Add(new BorderProgress(.25f+i*.14f));if(m.AutoCast[i]){var mark=Icon(b,m.Run.buffs.autoCast,32);mark.AddToClassList("ability-echo");mark.tintColor=m.Run.buffs.autoCastTint;}}var hero=E(lower,"surface hero");var content=E(hero,"row hero-content");var portrait=E(content,"hero-portrait-frame");Icon(portrait,m.Run.portrait,64);var vitals=E(content,"hero-vitals");var top=E(vitals,"row hero-vital-row");
   HeroStat(top,StatIconLookup.StatKey.Defense,"85.7%","defence");HeroStat(top,StatIconLookup.StatKey.Health,"3724/3724","health");Bar(vitals,100,"health");var below=E(vitals,"row hero-vital-row hero-below");HeroStat(below,StatIconLookup.StatKey.Regen,"131.776/s","regeneration");HeroStat(below,StatIconLookup.StatKey.MoveSpeed,"497.2%","movement");
   var breakdown=B(screen,"",ShowRunBreakdown,"run-breakdown");L(breakdown,T("breakdown"),"strong");L(breakdown,"+50% "+T("resources"),"small");
  }
  void HeroStat(VisualElement parent,StatIconLookup.StatKey key,string value,string label)
  {
   var item=E(parent,"row hero-stat");item.tooltip=T(label)+": "+value;
   StatIconLookup.TryGetIcon(key,out var sprite);Icon(item,sprite,18);L(item,value,"small strong");
  }
  void ShowRunBreakdown()
  {
   var box=Dialog(T("breakdown"));box.Clear();box.AddToClassList("breakdown-sheet");
   var header=E(box,"row breakdown-header");L(header,T("baseRate"),"small muted breakdown-rate");L(header,T("breakdown"),"heading breakdown-title");L(header,"04:32","strong breakdown-time");
   var scroll=Scroll(box,"run-ledger");var grid=E(scroll,"run-ledger-grid");
   string[] names={"Carrot","Wheat","Stone","Slime"};double[] counts={2350,3176,1900,1000};
   var resources=names.Select(n=>m.Resources.FirstOrDefault(r=>r.name==n)).Where(r=>r!=null).Concat(m.Resources.Where(r=>!names.Contains(r.name)).Take(8)).ToArray();
   for(int i=0;i<resources.Length;i++){var resource=resources[i];double count=i<counts.Length?counts[i]:125*(i+1);var entry=E(grid,"row ledger-entry");entry.tooltip=resource.name;Icon(entry,resource.icon,36);var values=E(entry,"ledger-values");L(values,T("earned")+": "+Short(count)+" ("+Short(count*1.5)+")","small strong");L(values,T("perMinute")+": "+Short(count*60/272)+" ("+Short(count*1.5*60/272)+")","small");}
   var footer=E(box,"row breakdown-footer");var left=E(footer,"ledger-footer-left");L(left,T("dismissOutside"),"small muted");L(left,T("distanceRate")+": 57","small");var right=E(footer,"ledger-footer-right");L(right,T("damageRate")+": 1,206","small");L(right,T("killRate")+": 8","small");
   header.tooltip=T("bonusNotation");box.focusable=true;box.Focus();modal.RegisterCallback<PointerDownEvent>(e=>{if(e.target==modal||e.button==1)CloseDialog();});
  }
  public void ApplyVariant(string variant){if(variant=="collection"||variant=="taste"){phoneTab=variant;Rebuild();}else if(variant=="confirm")ConfirmMix(false);else if(variant=="confirm-all")ConfirmMix(true);else if(variant=="breakdown")ShowRunBreakdown();else if(variant=="scrolled"){foodScroll?.schedule.Execute(()=>foodScroll.scrollOffset=new Vector2(0,foodScroll.verticalScroller.highValue)).StartingIn(200);}}
  public string Validate(){int images=0,invalid=0;root.Query<Image>().ForEach(i=>{if(i.sprite){images++;if(i.scaleMode!=ScaleMode.ScaleToFit)invalid++;}});var fs=root.Q<ScrollView>("ingredients-scroll");var cs=root.Q<ScrollView>("collection-scroll");var work=root.Q<VisualElement>("workspace");return $"Editor-only sample; Play={EditorApplication.isPlaying}\nTheme={dark}; locale={locale}; large={large}; narrow={narrow}\nFoods={m.Foods.Length}; resources={m.Resources.Length}; buffs={m.Buffs.Length}; boons={m.Boons.Length}\nImages={images}; invalid aspect modes={invalid}\nRoot={root.worldBound}; workspace={work?.worldBound}\nIngredients viewport={fs?.contentViewport.worldBound}; scroll range={fs?.verticalScroller.highValue}\nCollection viewport={cs?.contentViewport.worldBound}; scroll range={cs?.verticalScroller.highValue}\n";}
 }
 internal sealed class BorderProgress:VisualElement
 {
  static readonly CustomStyleProperty<Color> Accent=new("--ring-color"),Track=new("--ring-track");Color accent,track;
  public BorderProgress(float value){AddToClassList("border-progress");pickingMode=PickingMode.Ignore;RegisterCallback<CustomStyleResolvedEvent>(e=>{e.customStyle.TryGetValue(Accent,out accent);e.customStyle.TryGetValue(Track,out track);MarkDirtyRepaint();});generateVisualContent+=ctx=>{float w=contentRect.width-2,h=contentRect.height-2;if(w<=0||h<=0)return;var pts=new[]{new Vector2(1+w/2,1),new Vector2(1+w,1),new Vector2(1+w,1+h),new Vector2(1,1+h),new Vector2(1,1),new Vector2(1+w/2,1)};var p=ctx.painter2D;p.lineWidth=2;Draw(p,pts,2*(w+h),track);Draw(p,pts,2*(w+h)*Mathf.Clamp01(value),accent);};}
  static void Draw(Painter2D p,Vector2[] pts,float remaining,Color color){p.strokeColor=color;p.BeginPath();p.MoveTo(pts[0]);for(int i=1;i<pts.Length&&remaining>0;i++){float length=Vector2.Distance(pts[i-1],pts[i]);p.LineTo(Vector2.Lerp(pts[i-1],pts[i],Mathf.Min(remaining/length,1)));remaining-=length;}p.Stroke();}
 }
}
