// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_meetIvan = new UnifiedAchievement("meetIvan",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "eov.meetivan"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_5OEj6gREAIQBw"
#else
            "meetIvan"
#endif
            );

        public static UnifiedAchievement meetIvan
        {
            get { return s_meetIvan; }
        }

        private static readonly UnifiedAchievement s_mildred = new UnifiedAchievement("Mildred",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "eov.mildred"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_5OEj6gREAIQDg"
#else
            "Mildred"
#endif
            );

        public static UnifiedAchievement Mildred
        {
            get { return s_mildred; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_meetIvan,
            s_mildred,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "meetIvan", s_meetIvan },
            { "Mildred", s_mildred },
        };
    }
}
