// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string MeetIvan
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.meetivan";
#elif UNITY_EDITOR
                    return "MeetIvan";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Mildred
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.mildred";
#elif UNITY_EDITOR
                    return "Mildred";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Reached100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQFg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.reached100";
#elif UNITY_EDITOR
                    return "Reached100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Reached1000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.reached1000";
#elif UNITY_EDITOR
                    return "Reached1000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Reached10000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQHg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.reached10000";
#elif UNITY_EDITOR
                    return "Reached10000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kilometers1
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQFw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.kilometers1";
#elif UNITY_EDITOR
                    return "Kilometers1";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kilometers100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQIA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.kilometers100";
#elif UNITY_EDITOR
                    return "Kilometers100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kilometers1000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQGA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.kilometers1000";
#elif UNITY_EDITOR
                    return "Kilometers1000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Tasks100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.tasks100";
#elif UNITY_EDITOR
                    return "Tasks100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Tasks5k
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQJg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.tasks5k";
#elif UNITY_EDITOR
                    return "Tasks5k";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Tasks25k
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQHw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.tasks25k";
#elif UNITY_EDITOR
                    return "Tasks25k";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MeetBarkley
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.meetbarkley";
#elif UNITY_EDITOR
                    return "MeetBarkley";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Buffs1
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQIw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.buffs1";
#elif UNITY_EDITOR
                    return "Buffs1";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Buffs2
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQGw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.buffs2";
#elif UNITY_EDITOR
                    return "Buffs2";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Buffs3
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQIg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.buffs3";
#elif UNITY_EDITOR
                    return "Buffs3";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Buffs4
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQIQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.buffs4";
#elif UNITY_EDITOR
                    return "Buffs4";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Buffs5
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQEg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.buffs5";
#elif UNITY_EDITOR
                    return "Buffs5";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Enemies1
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQFA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.enemies1";
#elif UNITY_EDITOR
                    return "Enemies1";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Enemies2
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQBA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.enemies2";
#elif UNITY_EDITOR
                    return "Enemies2";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Enemies3
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQDQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.enemies3";
#elif UNITY_EDITOR
                    return "Enemies3";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Enemies4
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQHA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.enemies4";
#elif UNITY_EDITOR
                    return "Enemies4";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Enemies5
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQKA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.enemies5";
#elif UNITY_EDITOR
                    return "Enemies5";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MeetGill
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.meetgill";
#elif UNITY_EDITOR
                    return "MeetGill";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MeetFarmers
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQGQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.meetfarmers";
#elif UNITY_EDITOR
                    return "MeetFarmers";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MeetOldTimer
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQEA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.meetoldtimer";
#elif UNITY_EDITOR
                    return "MeetOldTimer";
#else
                    return string.Empty;
#endif
                }
            }

            public static string EvaLevel10
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQAw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.evalevel10";
#elif UNITY_EDITOR
                    return "EvaLevel10";
#else
                    return string.Empty;
#endif
                }
            }

            public static string EvaLevel50
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQEw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.evalevel50";
#elif UNITY_EDITOR
                    return "EvaLevel50";
#else
                    return string.Empty;
#endif
                }
            }

            public static string EvaLevel100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQJQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.evalevel100";
#elif UNITY_EDITOR
                    return "EvaLevel100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string EvaLevel200
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQFQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.evalevel200";
#elif UNITY_EDITOR
                    return "EvaLevel200";
#else
                    return string.Empty;
#endif
                }
            }

            public static string EvaLevel500
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQJw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.evalevel500";
#elif UNITY_EDITOR
                    return "EvaLevel500";
#else
                    return string.Empty;
#endif
                }
            }

            public static string IvanLevel10
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQGg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.ivanlevel10";
#elif UNITY_EDITOR
                    return "IvanLevel10";
#else
                    return string.Empty;
#endif
                }
            }

            public static string IvanLevel50
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQEQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.ivanlevel50";
#elif UNITY_EDITOR
                    return "IvanLevel50";
#else
                    return string.Empty;
#endif
                }
            }

            public static string IvanLevel100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.ivanlevel100";
#elif UNITY_EDITOR
                    return "IvanLevel100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string IvanLevel500
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQDw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.ivanlevel500";
#elif UNITY_EDITOR
                    return "IvanLevel500";
#else
                    return string.Empty;
#endif
                }
            }

            public static string IvanLevel1000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQDA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.ivanlevel1000";
#elif UNITY_EDITOR
                    return "IvanLevel1000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Die10
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQHQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.die10";
#elif UNITY_EDITOR
                    return "Die10";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Die250
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQBg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.die250";
#elif UNITY_EDITOR
                    return "Die250";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Die1000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI_5OEj6gREAIQJA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "eov.die1000";
#elif UNITY_EDITOR
                    return "Die1000";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
        }
    }
}
