using System;using System.Collections.Generic;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.UIElements;using TimelessEchoes.UI;using TimelessEchoes.UI.Toolkit;using TimelessEchoes.References.StatPanel;using TimelessEchoes.References.UI;using Image=UnityEngine.UI.Image;
namespace TimelessEchoes.EditorTools
{
 public static class ToolkitStatisticsMigration
 {
  [MenuItem("Tools/UI Toolkit/Import Statistics reference")]
  public static void Import()
  {
   if(Application.isPlaying)throw new InvalidOperationException("Main Edit mode required");const string path="Assets/UI/Toolkit/";
   var wm=new SerializedObject(UnityEngine.Object.FindAnyObjectByType<TownWindowManager>(FindObjectsInactive.Include));var window=((GameObject)wm.FindProperty("stats").FindPropertyRelative("window").objectReferenceValue).transform;
   var d=AssetDatabase.LoadAssetAtPath<ToolkitStatisticsDefinition>(path+"Statistics.asset");if(!d){d=ScriptableObject.CreateInstance<ToolkitStatisticsDefinition>();AssetDatabase.CreateAsset(d,path+"Statistics.asset");}
   var button=window.Find("Image/Buttons/GameObject/General_Button").GetComponent<UnityEngine.UI.Button>();d.button=button.GetComponent<Image>().sprite;d.selectedButton=button.spriteState.disabledSprite;d.selectedTint=button.transition==UnityEngine.UI.Selectable.Transition.SpriteSwap?Color.white:button.colors.disabledColor;d.selectedText=button.transform.Find("Disabled_Text (TMP) (1)").GetComponent<TMPro.TMP_Text>().color;
   d.panel=window.Find("Image/ScrollViews").GetComponent<Image>().sprite;d.inset=window.Find("Image/ScrollViews/BG").GetComponent<Image>().sprite;
   var general=window.Find("Image/ScrollViews/BG/General/Viewport/Content/General Stats");d.row=general.GetComponent<Image>().sprite;var icon=general.Find("Horizontal/Enemy_Image");d.iconFrame=icon.GetComponent<Image>().sprite;d.portraitFrame=icon.Find("Image").GetComponent<Image>().sprite;d.portrait=icon.Find("Image/EnemyIcon").GetComponent<Image>().sprite;
   var gm=new SerializedObject(TimelessEchoes.GameManager.Instance?TimelessEchoes.GameManager.Instance:UnityEngine.Object.FindAnyObjectByType<TimelessEchoes.GameManager>(FindObjectsInactive.Include));var entries=gm.FindProperty("generationButtons");var maps=new List<ToolkitStatisticsDefinition.MapEntry>();
   for(int i=0;i<entries.arraySize;i++){var e=entries.GetArrayElementAtIndex(i);var ui=(GeneralStatsUIReferences)e.FindPropertyRelative("statsUI").objectReferenceValue;if(!ui)continue;var label=ui.transform.Find("Horizontal/Enemy_Image/Name").GetComponent<TMPro.TMP_Text>();maps.Add(new ToolkitStatisticsDefinition.MapEntry{config=(TimelessEchoes.MapGeneration.MapGenerationConfig)e.FindPropertyRelative("config").objectReferenceValue,icon=ui.GetComponentsInChildren<Image>(true).First(image => image.name == "EnemyIcon").sprite,label=label.text,labelSize=label.fontSize,killScaling=e.FindPropertyRelative("scalingMode").enumValueIndex==1});}d.maps=maps.ToArray();
   var ranks=new SerializedObject(UnityEngine.Object.FindAnyObjectByType<LeaderboardsPanelUI>(FindObjectsInactive.Include));var player=(LeaderboardEntryUI)ranks.FindProperty("playerEntry").objectReferenceValue;d.playerRow=player.GetComponent<Image>().sprite;
   var itemUI=new SerializedObject(UnityEngine.Object.FindAnyObjectByType<ItemStatsPanelUI>(FindObjectsInactive.Include));var refs=(StatPanelReferences)itemUI.FindProperty("references").objectReferenceValue;d.itemTiers=refs.tierBackgroundSprites.ToArray();
   var taskUI=new SerializedObject(UnityEngine.Object.FindAnyObjectByType<TaskStatsPanelUI>(FindObjectsInactive.Include));var taskRefs=(StatPanelReferences)taskUI.FindProperty("references").objectReferenceValue;var taskEntry=taskRefs.taskEntryPrefab.GetComponent<TaskStatEntryUIReferences>();d.toggleOn=taskEntry.toggleOnSprite;d.toggleOff=taskEntry.toggleOffSprite;
   var enemyUI=new SerializedObject(UnityEngine.Object.FindAnyObjectByType<EnemyStatsPanelUI>(FindObjectsInactive.Include));var enemyRefs=(StatPanelReferences)enemyUI.FindProperty("references").objectReferenceValue;var enemyEntry=enemyRefs.enemyEntryPrefab.GetComponent<EnemyStatEntryUIReferences>();d.progressTrack=enemyEntry.progressBar.GetComponent<Image>().sprite;d.progressFill=enemyEntry.nextRevealProgressBar.sprite;
   var options=AssetDatabase.LoadAssetAtPath<ToolkitOptionsDefinition>(path+"Options.asset");d.sliderTrack=options.sliderTrack;d.sliderFill=options.sliderFill;d.sliderHandle=options.sliderHandle;
   var runs=UnityEngine.Object.FindAnyObjectByType<RunStatsPanelUI>(FindObjectsInactive.Include);var rs=new SerializedObject(runs);var first=(RunBarUI)rs.FindProperty("runBars").GetArrayElementAtIndex(0).objectReferenceValue;var bs=new SerializedObject(first);d.graphFill=((Image)bs.FindProperty("fillImage").objectReferenceValue).sprite;d.graphFrame=first.transform.parent.GetComponent<Image>().sprite;
   var average=(UnityEngine.UI.Slider)rs.FindProperty("averageRunSlider").objectReferenceValue;var averageImage=average.handleRect.GetComponent<Image>();d.averageLine=averageImage.sprite;d.averageColor=averageImage.color;
   ToolkitStatisticsDefinition.GraphColors Colors(string prefix)=>new(){death=rs.FindProperty(prefix+"DeathBarColor").colorValue,retreat=rs.FindProperty(prefix+"RetreatBarColor").colorValue,abandoned=rs.FindProperty(prefix+"AbandonedBarColor").colorValue,reaped=rs.FindProperty(prefix+"ReapedBarColor").colorValue};
   d.distanceColors=new(){death=rs.FindProperty("deathBarColor").colorValue,retreat=rs.FindProperty("retreatBarColor").colorValue,abandoned=rs.FindProperty("abandonedBarColor").colorValue,reaped=rs.FindProperty("reapedBarColor").colorValue};d.resourceColors=Colors("resources");d.resourceColors.bonus=rs.FindProperty("resourcesBonusBarColor").colorValue;d.killColors=Colors("kills");
   var tooltip=(RunStatUIReferences)rs.FindProperty("runStatUI").objectReferenceValue;d.tooltipLeft=tooltip.leftSprite;d.tooltipRight=tooltip.rightSprite;EditorUtility.SetDirty(d);
   var go=new GameObject("Toolkit Statistics");try{var native=new SerializedObject(go.AddComponent<ToolkitStatisticsScreen>());native.FindProperty("definition").objectReferenceValue=d;native.FindProperty("theme").objectReferenceValue=AssetDatabase.LoadAssetAtPath<ToolkitTheme>(path+"Theme.asset");native.FindProperty("runtimeTheme").objectReferenceValue=AssetDatabase.LoadAssetAtPath<ThemeStyleSheet>(path+"Runtime.tss");native.FindProperty("textSettings").objectReferenceValue=AssetDatabase.LoadAssetAtPath<PanelTextSettings>(path+"TextSettings.asset");native.ApplyModifiedPropertiesWithoutUndo();PrefabUtility.SaveAsPrefabAsset(go,path+"Statistics.prefab");AssetDatabase.SaveAssets();}finally{UnityEngine.Object.DestroyImmediate(go);}
  }
 }
}

